var list = [
  "beer",
  "sausage roll",
  "salmon",
  "detergent",
  "soap",
  "salami",
  "cottage cheese",
  "pizza",
  "foil",
  "soreen",
  "loo roll",
  "cheddar",
  "cif",
  "tupperware",
  "scissors",
  "breadknife",
  "orange juice",
  "sardines",
  "cheese",
  "tampons",
  "ciabatta",
  "super glue",
  "memory foam mattress",
  "steak and ale pie",
  "pilchards",
  "lemon tart",
  "immodium",
  "dog food",
  "lemons",
  "gravy granules",
  "soup",
  "carrots",
  "nuts",
  "olbas oil",
  "shampoo",
  "herbal essences",
  "strepsils",
  "ibuprofen",
  "floppy disc",
  "walkman",
  "cassette",
  "now that's what I call music 42",
  "Rosemary Conley exercise video",
  "leg warmers",
  "bendy ruler",
  "gel pen",
  "hubba bubba",
  "apple",
  "furby",
  "scrunchies",
  "jelly shoes",
  "Bikergrove boxset",
  "Gareth Gates poster",
  "meatballs",
  "celery",
  "toothpick",
  "jelly",
  "avocado",
  "Will Smith CD",
  "milk",
  "flour",
  "raisins",
  "crisps",
  "mille feuille",
  "chocolate",
  "biscuits",
  "sugar",
  "ketchup",
  "salt",
  "pepper",
  "tuna",
  "crab sticks",
  "ibuprofen",
  "calpol",
  "parsley",
  "cinnamon",
  "golden nuggets",
  "paper",
  "ink",
  "fountain pen",
  "headphones",
  "pineapple",
  "ham",
  "Radio Times",
  "Gardener's World",
  "Britney Spears filofax",
  "napkins"
];
